apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
  annotations:
  # keep these to avoid preview/dry-run errors before CRDs are visible
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-ca
  namespace: cert-manager
  annotations:
  # keep these to avoid preview/dry-run errors before CRDs are visible
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  isCA: true
  secretName: homelab-ca-keypair
  commonName: Homelab Root CA
  subject:
    organizations: ["Homelab"]
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: homelab-ca
  annotations:
  # keep these to avoid preview/dry-run errors before CRDs are visible
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  ca:
    secretName: homelab-ca-keypair
