apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-deploy-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/colinchaput/homelab-gitops
    targetRevision: HEAD
    path: apps/platform/_applications
    directory:
      recurse: false
      include: "*-app.yaml"        # ← only Application CRs are picked up
      #exclude: '**/manifests/**'   # <— critical so raw CRs aren't applied by the parent
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      prune: true
      selfHeal: true
