apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-deploy
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/colinchaput/homelab-gitops
    targetRevision: HEAD
    path: apps/root/children
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
