apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-platform-deploy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/colinchaput/homelab-gitops
    targetRevision: HEAD
    path: apps_old/platform
    directory:
      recurse: true
      exclude: '**/manifests/**'   # <— critical so raw CRs aren't applied by the parent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
