apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    # 1) The Helm chart source (official ingress-nginx chart)
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.11.2   # Pin a version; update as needed
      helm:
        valueFiles:
          # Pull values.yaml from the Git repo source defined below
          - $values/apps/platform/ingress-nginx/values.yaml

    # 2) Your Git repo source that holds the values.yaml
    - repoURL: https://github.com/colinchaput/homelab-gitops
      targetRevision: HEAD
      ref: values
