---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel
  namespace: cloudflared
spec:
  encryptedData:
    token: AgAI2w7ByyxMyDfdW1sny/zLYOnsBWHtdm34dj7ydocqOhLnJKUf2q5JBpFEKUYqwmr157e466UGN/OzFqVPMIWtiW7dot5ir8pW0+BUKFiWSsvYvbswOgLAigzOAGWhO9no/j1dEILndyivWX9xyPjnbCcHl32nCMcST8CVpLdtmoSI8Ak4BGTEZrJtJVk68eZ5flUw7f8vJdOV2IKO9GUMXlYV/g/ED6+0CGHvfkjZtMrpUkq4AFaaKJMa0hJqrQQUCNvEeLGm7EB2+m2IalZw+g97ptCEJhG1GJgZYyFRQy0FZyTi6ZVl5C2iZUYCxSewyZXPLCq7een1oEvu+p2d2+rGmSg+nrnmE+SBYJ0r24JQysH++PDW7PssOfZ0uf7eJWGbxCfjFs4mv2DdbibbURAHhKj2py4JU/iTUK6oYTGNih3eIqcz8FlnkmatYU9a8+I5is9mauDKoxfR/22KjHtLa1iBsy3ayjK8XVVPvyg+20YHquekTFrcmPJYdMI5b0pY98Ri1SRF6v8p0D0tz3FMyV09keo2gKdQTVxmy21w8ZMUnoisNniUn+E3KvPEswDvaaP9u/Exr/FXWaCb9h7KoSPzPmQ9U9liRMSnQoU8V6ncjDeH5dwyEHqHrBUn6WF4b9OL4KDN4VhWotZoX1bOeVphKfSG6HkphVz5metuzQxSSvDMWtNGXYn2FbX4RlspR6b2cKz77dBjctHdv2ZcGEVLIPWK0jo9t5Q3GN+8eGTFro70KXGvcHpWfsKlJd4XnWQOYchCBjfwtVn3BMjXdO1Th4lFqtqhcTSP3uFlPmp19yrqhpaBJ7L24rf/VTr5XS6+gKY1ROctay+IOAWvsAVtRehbe9GIoCkRxgJzXEc7Ty1zYB4XtqpKvee8Rc331HBx2nW9J9VBqc2RPpewvHp/pWngy0Z1ZDguh8Gf4nSnpb5n
  template:
    metadata:
      name: cloudflared-tunnel
      namespace: cloudflared
