apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"   # must come AFTER metallb
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  source:
    repoURL: https://github.com/colinchaput/homelab-gitops
    targetRevision: HEAD
    path: apps/platform/metallb-config/manifests
